# User Setting
gmail:
  username: monthly.code
github:
  username: monthly-code
gitlab:
  username: 
google-analytics: 
  ua:
disqus:
  username: monthly-code

username: Monthly Code
# Site Path Setting
host:
port:
url: 
baseurl: 

# Search
search: true

# Site Info Setting
title: monthly code's _Template site
intro: >
  Intro message!

# Permalink Setting
permalink: pretty

# Paginator Setting
paginator:
  size: 5

# Collection Setting
collections:
  docs:
    output: true
    permalink: /:collection/:path
  journals:
    output: true
    permalink: /:collection/:path
  tags:
    output: true
    permalink: /:collection/:path
  categories:
    output: true
    permalink: /:collection/:path
  jekyll:
    output: true
  gitlab:
    output: true

# Default Setting
defaults:
  -
    scope:
      path: _jekyll
      type: jekyll # candidate only collection name
    values:
      permalink: docs/jekyll/:title
  -
    scope:
      path: _gitlab
      type: gitlab
    values:
      permalink: docs/gitlab/:title

# Markdown Setting
markdown: kramdown
kramdown:
  highlighter: rouge
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true
  # input: GFM

# Build Setting
exclude:
  - Gemfile
  - Gemfile.lock